### ISSUE TITLE
Spark-cluster in NCSR-cluster

### ISSUE THREAD

**Issue by gioargyr** [big-data-europe/README#2]
Hi! There is a docker-spark-cluster up&running the last 7 days in NCSR's cluster (from bde2020/spark-_:1.5.1-hadoop2.6). I submitted a spark-job and I got a spark-related error(https://github.com/big-data-europe/docker-spark/issues/4).
I tried to run the next version of docker-spark (bde2020/spark-_:1.6.2-hadoop2.6), but the workers can't connect to the master, possibly because there is the already up&running spark-cluster.
- Who else is using the up&running docker-spark-cluster?
- Can I freely stop it whenever I want?
- Can we stop it and run the newer version?

**Comment by acharal** [comment]
Hi Giorgos,
The Docker instances you are referring to are leftovers from an experiment we (NCSR-D) were running. I shut them down. You can start you own spark cluster. 

As a note, I think that it is desired to be able to have 2 different versions of spark up&running at the cluster without interfering with each other. I think the problems you have encountered are due to the fact that the spark workers are trying to connect to the predefined "spark-master". Do anyone know if it is possible to configure:
- a docker spark master with a different container_name than "spark-master"
- the docker spark workers to register to a different master other than "spark-master"

**Comment by erikap** [comment]
Hi @gioargyr and @acharal,

if the 2 Spark clusters reside in different docker-compose files, they should not collide. By default they will be attached to different overlay networks. Unless the same overlay network is specified in both docker-compose files?

If you want to use another name than 'spark-master', you have to:
- update the hostname set on the Spark Master container (e.g. `hostname: my-new-spark-master`)
- update the alias of the link with the spark-worker (e.g. `master:my-new-spark-master`)
- set the `SPARK_MASTER` environment variable on the Spark worker container. The URL should include the new name of the Spark master (e.g. `spark://my-new-spark-master:7077`) 
- set the `SPARK_MASTER_NAME` environment variable on the Spark application container.
