### ISSUE TITLE
container fails to run

### ISSUE THREAD

**Issue by gioargyr** [big-data-europe/README#7]
Hi all,
The last days sometimes when I try to run a container I get the following error from NCSR-D cluster:

docker: Error response from daemon: Error response from daemon: container 747902e7f56771285f777b1a97b6051432c7dd4b37efaa07e48bd316e149d92c: endpoint join on GW Network failed: driver failed programming external connectivity on endpoint gateway_747902e7f567 (a44e45d2ee7762ff32493ec5b096a6201c076a31cf7bca8555cda963524f9a88): Bind for 0.0.0.0:8190 failed: port is already allocated.

Most of the times I surpass the error by changing the mapped port. 
I get the error when I run this:
docker -H tcp://master:4000 run --name sextant --net=bde_net -e constraint:node==slave1 -p 8190:8080 bde2020/sextant:2.0.0

But, it works fine if I change it to:
docker -H tcp://master:4000 run --name sextant --net=bde_net -e constraint:node==slave1 -p 8191:8080 bde2020/sextant:2.0.0

BUT! In case of Sextant we need to run it exclusively in slave1 and port 8190 in order for the SC7Pilot to be accessible from everywhere.
Despite the error says, the slave1:8190 is free and there's no other container named "sextant" in the cluster.

**Comment by gmouchakis** [comment]
@gioargyr I'm not sure why the port isn't released. There are several issues about this in the docker issue tracker but I can't find a solution that works all the time. If we restart the docker service the port will be probably released but in order to avoid restarting all the containers I changed the port forwarding and now you can use port 8191 for sextant. Please verify that everything works now.

**Comment by gioargyr** [comment]
Hi again. This is an issue that I came up several times the last days with other containers too, but only the case of sextant was of great importance.
Now I run docker-sextant mapped in slave1:8191 and it works fine.
Thank you very much for the instant response.
